# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-13 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oil', models.IntegerField(default=750, verbose_name='Oil')),
                ('iron', models.IntegerField(default=750, verbose_name='Iron')),
                ('wood', models.IntegerField(default=750, verbose_name='Wood')),
                ('food', models.IntegerField(default=750, verbose_name='Food')),
            ],
        ),
        migrations.CreateModel(
            name='Troop_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('Infantry', 'Infantry'), ('Aviation', 'Aviation'), ('Artilery', 'Artilery'), ('Navy', 'Navy')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Troops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_time', models.TimeField()),
                ('training_time', models.TimeField()),
                ('image', models.ImageField(upload_to=b'')),
                ('description', models.TextField(max_length=2550)),
                ('name', models.CharField(max_length=25)),
                ('consumption', models.IntegerField()),
                ('attack_power', models.IntegerField()),
                ('def_infantry', models.IntegerField()),
                ('def_artilery', models.IntegerField()),
                ('def_aviation', models.IntegerField()),
                ('def_marine', models.IntegerField()),
                ('icon', models.ImageField(blank=True, default=None, null=True, upload_to=b'')),
                ('carry', models.IntegerField(default=0)),
                ('destruction_power', models.IntegerField(default=0)),
                ('speed', models.IntegerField(default=0)),
                ('research_cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='troops.Resources')),
                ('training_cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_cost', to='troops.Resources')),
                ('troop_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='troops.Troop_type')),
                ('upgrade_cost', models.ManyToManyField(null=True, related_name='Upgrade', to='troops.Resources')),
            ],
        ),
    ]
