# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 09:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('troops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='troops',
            name='training_cost',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='training_cost', to='troops.Resources'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='troops',
            name='training_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
