# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-14 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpgradeResources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oil', models.IntegerField(default=750, verbose_name='Oil')),
                ('iron', models.IntegerField(default=750, verbose_name='Iron')),
                ('wood', models.IntegerField(default=750, verbose_name='Wood')),
                ('food', models.IntegerField(default=750, verbose_name='Food')),
                ('lvl', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='troops',
            name='upgrade_cost',
            field=models.ManyToManyField(null=True, related_name='Upgrade', to='troops.UpgradeResources'),
        ),
    ]
