# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-08 18:56
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('building', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alliance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_population', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ally_leadership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=50)),
                ('mm_rights', models.BooleanField()),
                ('diplomacy', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='American_troops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Army',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('activation', models.DateTimeField()),
                ('activated', models.BooleanField()),
                ('typ', models.CharField(choices=[('Atom', 'Atom core'), ('Concrete', 'Reinforced concrete'), ('Nitro', 'Nytrogen'), ('Spy', 'Spy'), ('Dehytrated', 'Dehydrated food'), ('Baby boom', 'Baby boom'), ('Masterplan', 'Large masterplan'), ('Sarin', 'Sarin')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Artifacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arti', models.ManyToManyField(to='world.Artifact')),
            ],
        ),
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_type', models.CharField(choices=[('Reinforcement', 'Reinforcement'), ('Full attack', 'Full attack'), ('Raid', 'Raid')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Barracks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold_club', models.BooleanField(default=False, verbose_name='Gold club')),
                ('plus_account', models.DateTimeField(default=datetime.datetime(2017, 6, 8, 18, 56, 31, 746408), verbose_name='Plus Account')),
                ('oil_bonus_production', models.DateTimeField(default=datetime.datetime(2017, 6, 8, 18, 56, 31, 746466), verbose_name='Oil bonus production')),
                ('iron_bonus_production', models.DateTimeField(default=datetime.datetime(2017, 6, 8, 18, 56, 31, 746516), verbose_name='Iron bonus production')),
                ('wood_bonus_production', models.DateTimeField(default=datetime.datetime(2017, 6, 8, 18, 56, 31, 746559), verbose_name='Wood bonus production')),
                ('food_bonus_production', models.DateTimeField(default=datetime.datetime(2017, 6, 8, 18, 56, 31, 746602), verbose_name='Food bonus production')),
            ],
        ),
        migrations.CreateModel(
            name='Brittish_troops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lvl', models.IntegerField(default=0)),
                ('building', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='building.Building')),
            ],
        ),
        migrations.CreateModel(
            name='BuildingQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.IntegerField()),
                ('start', models.DateTimeField(default=None, null=True)),
                ('end', models.DateTimeField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.Building')),
            ],
        ),
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_01', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Typeone', to='world.Building')),
                ('pos_02', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Typetwo', to='world.Building')),
                ('pos_03', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Typethree', to='world.Building')),
                ('pos_04', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Typefour', to='world.Building')),
                ('pos_05', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Typefive', to='world.Building')),
                ('pos_06', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Typesix', to='world.Building')),
                ('pos_07', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Typeseven', to='world.Building')),
                ('pos_08', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Typeeight', to='world.Building')),
                ('pos_09', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Typenine', to='world.Building')),
                ('pos_10', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Typeten', to='world.Building')),
                ('pos_11', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Typeeleven', to='world.Building')),
                ('pos_12', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Typetwelve', to='world.Building')),
                ('pos_13', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Typethreet', to='world.Building')),
                ('pos_14', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Typefourt', to='world.Building')),
                ('pos_15', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Typefivet', to='world.Building')),
                ('pos_16', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Typesixt', to='world.Building')),
                ('pos_17', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Typesevent', to='world.Building')),
                ('pos_18', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Typeeightt', to='world.Building')),
                ('pos_19', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Typeninet', to='world.Building')),
                ('pos_20', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Typetwenty', to='world.Building')),
                ('pos_21', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Typeto', to='world.Building')),
                ('pos_22', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Typett', to='world.Building')),
                ('pos_23', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Typetth', to='world.Building')),
                ('pos_24', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Typetf', to='world.Building')),
            ],
        ),
        migrations.CreateModel(
            name='Defender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('army', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.Army')),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lvl', models.IntegerField(default=0)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='building.Field')),
            ],
        ),
        migrations.CreateModel(
            name='FieldQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.IntegerField()),
                ('start', models.DateTimeField(default=None, null=True)),
                ('end', models.DateTimeField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.Field')),
            ],
        ),
        migrations.CreateModel(
            name='Fields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_01', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Typeone', to='world.Field')),
                ('pos_02', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Typetwo', to='world.Field')),
                ('pos_03', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Typethree', to='world.Field')),
                ('pos_04', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Typefour', to='world.Field')),
                ('pos_05', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Typefive', to='world.Field')),
                ('pos_06', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Typesix', to='world.Field')),
                ('pos_07', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Typeseven', to='world.Field')),
                ('pos_08', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Typeeight', to='world.Field')),
                ('pos_09', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Typenine', to='world.Field')),
                ('pos_10', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Typeten', to='world.Field')),
                ('pos_11', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Typeeleven', to='world.Field')),
                ('pos_12', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Typetwelve', to='world.Field')),
                ('pos_13', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Typethreet', to='world.Field')),
                ('pos_14', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Typefourt', to='world.Field')),
                ('pos_15', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Typefivet', to='world.Field')),
                ('pos_16', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Typesixt', to='world.Field')),
                ('pos_17', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Typesevent', to='world.Field')),
                ('pos_18', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Typeeightt', to='world.Field')),
            ],
        ),
        migrations.CreateModel(
            name='German_troops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Hangar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('experience', models.IntegerField(default=0, verbose_name='Hero experience')),
                ('level', models.IntegerField(default=0, verbose_name='Hero level')),
                ('health', models.IntegerField(default=100, verbose_name='Health')),
                ('strength', models.IntegerField(default=100, verbose_name='Hero strength')),
                ('attack_bonus', models.IntegerField(default=0, verbose_name='Attack bonus ')),
                ('defense_bonus', models.IntegerField(default=0, verbose_name='Defense bonus ')),
                ('gold_bonus', models.IntegerField(default=0, verbose_name='Gold bonus')),
                ('resources', models.IntegerField(default=0, verbose_name='Resource bonus')),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ally', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.Alliance')),
            ],
        ),
        migrations.CreateModel(
            name='Japanese_troops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Market_offers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Market_resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oil', models.IntegerField(verbose_name='Oil')),
                ('iron', models.IntegerField(verbose_name='Iron')),
                ('coal', models.IntegerField(verbose_name='Coal')),
                ('food', models.IntegerField(verbose_name='Food')),
            ],
        ),
        migrations.CreateModel(
            name='Medals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.IntegerField()),
                ('week', models.IntegerField()),
                ('medal', models.CharField(choices=[('Attack', '%d. attacker of the week %d'), ('Defense', '%d. defender of the week  %d'), ('Raiding', '%d. robber of the week %d'), ('Climber', '%d. climber of the week %d')], max_length=10)),
                ('image', models.ImageField(upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=10000000000)),
                ('subject', models.CharField(max_length=255)),
                ('read', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Naps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField()),
                ('ally_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ally_1', to='world.Alliance')),
                ('ally_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ally_2', to='world.Alliance')),
            ],
        ),
        migrations.CreateModel(
            name='Oasis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_latitude', models.IntegerField()),
                ('location_longitude', models.IntegerField()),
                ('bonus_1', models.IntegerField()),
                ('bonus_2', models.IntegerField(null=True)),
                ('army', models.ManyToManyField(to='world.Army')),
            ],
        ),
        migrations.CreateModel(
            name='Partisan_troops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('population', models.IntegerField(default=2, verbose_name='Population')),
                ('gold', models.IntegerField(default=30, verbose_name='Gold')),
                ('last_login', models.DateTimeField(default=datetime.datetime(2017, 6, 8, 18, 56, 31, 754415))),
                ('artifact_holder', models.BooleanField(default=False)),
                ('culture_points', models.IntegerField(default=0)),
                ('old_rank', models.IntegerField()),
                ('raided', models.IntegerField(default=0)),
                ('attack_points', models.IntegerField(default=0)),
                ('def_points', models.IntegerField(default=0)),
                ('old_att', models.IntegerField(default=0)),
                ('old_def', models.IntegerField(default=0)),
                ('banned', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('activation_key', models.CharField(max_length=25, null=True)),
                ('profile', models.TextField(max_length=1000, null=True)),
                ('notes', models.TextField(max_length=1000, null=True)),
                ('location', models.CharField(choices=[('ne', 'North East'), ('nw', 'North West'), ('se', 'South East'), ('sw', 'South West')], max_length=5)),
                ('next_update', models.DateTimeField(default=None, null=True)),
                ('bonuses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.Bonus')),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.Hero')),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('next_update', models.DateTimeField(default=datetime.datetime(2017, 6, 8, 18, 56, 31, 734399))),
                ('last_update', models.DateTimeField()),
                ('building_lvl', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField()),
                ('time_stamp', models.DateTimeField()),
                ('attack_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.Attack')),
                ('attacker_army', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.Army')),
            ],
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oil', models.FloatField(default=750, verbose_name='Oil')),
                ('iron', models.FloatField(default=750, verbose_name='Iron')),
                ('wood', models.FloatField(default=750, verbose_name='Wood')),
                ('food', models.FloatField(default=750, verbose_name='Food')),
            ],
        ),
        migrations.CreateModel(
            name='Russian_troops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Scouting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField()),
                ('time_stamp', models.DateTimeField()),
                ('attacker_army', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.Army')),
            ],
        ),
        migrations.CreateModel(
            name='Trading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Trading_resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oil', models.IntegerField()),
                ('iron', models.IntegerField()),
                ('coal', models.IntegerField()),
                ('food', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Partisans', 'Partisans'), ('Russians', 'Russians'), ('Americans', 'Americans'), ('Brittish', 'Brittish'), ('Germans', 'Germans'), ('Japanese', 'Japanese')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Troop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('training_time_per_unit', models.IntegerField()),
                ('cost_oil', models.IntegerField()),
                ('cost_iron', models.IntegerField()),
                ('cost_coal', models.IntegerField()),
                ('cost_food', models.IntegerField()),
                ('consumption', models.IntegerField()),
                ('attack_power', models.IntegerField()),
                ('def_infantry', models.IntegerField()),
                ('def_artilery', models.IntegerField()),
                ('def_aviation', models.IntegerField()),
                ('def_marine', models.IntegerField()),
                ('icon', models.ImageField(upload_to=b'')),
                ('picture', models.ImageField(upload_to=b'')),
                ('carry', models.IntegerField(default=0)),
                ('destruction_power', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Troop_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('Infantry', 'Infantry'), ('Aviation', 'Aviation'), ('Artilery', 'Artilery'), ('Marine', 'Marine')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Troops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='Troops count')),
                ('upgrade', models.IntegerField(default=0, verbose_name='Upgrade level of troops')),
            ],
        ),
        migrations.CreateModel(
            name='Update_negative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empty_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=26, null=True)),
                ('location_latitude', models.IntegerField(null=True)),
                ('location_longitude', models.IntegerField(null=True)),
                ('population', models.IntegerField(default=0)),
                ('capital', models.BooleanField(default=True)),
                ('update', models.DateTimeField(default=datetime.datetime(2017, 6, 8, 18, 56, 31, 742237), null=True, verbose_name='Last update time')),
                ('culture_points', models.IntegerField(default=0)),
                ('storage_capacity', models.IntegerField(default=800)),
                ('food_capacity', models.IntegerField(default=800)),
                ('next_update', models.DateTimeField(default=None, null=True)),
                ('parliament', models.BooleanField(default=False)),
                ('free_crop', models.IntegerField()),
                ('army', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='world.Army')),
                ('bonus', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonus', to='world.Resources')),
                ('building_1', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='world.BuildingQueue')),
                ('building_2', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Secondary', to='world.BuildingQueue')),
                ('center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='world.Center')),
                ('field_1', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='world.FieldQueue')),
                ('field_2', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Secondary', to='world.FieldQueue')),
                ('fields', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='world.Fields')),
                ('production', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Production', to='world.Resources')),
                ('real_production', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='real', to='world.Resources')),
                ('reinforcements', models.ManyToManyField(null=True, related_name='reinforcements', to='world.Army')),
                ('resources', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Resources', to='world.Resources')),
            ],
        ),
        migrations.CreateModel(
            name='VillageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oil_field', models.IntegerField()),
                ('forrest', models.IntegerField()),
                ('iron_mine', models.IntegerField()),
                ('farm', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue', models.ManyToManyField(to='world.Queue')),
            ],
        ),
        migrations.AddField(
            model_name='village',
            name='typ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.VillageType'),
        ),
        migrations.AddField(
            model_name='update_negative',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.Village'),
        ),
        migrations.AddField(
            model_name='troop',
            name='troop_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.Troop_type'),
        ),
        migrations.AddField(
            model_name='trading',
            name='quantity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.Trading_resources'),
        ),
        migrations.AddField(
            model_name='trading',
            name='recipent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Recipent', to='world.Village'),
        ),
        migrations.AddField(
            model_name='trading',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sender', to='world.Village'),
        ),
        migrations.AddField(
            model_name='scouting',
            name='attacker_village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.Village'),
        ),
        migrations.AddField(
            model_name='scouting',
            name='defenders',
            field=models.ManyToManyField(to='world.Defender'),
        ),
        migrations.AddField(
            model_name='russian_troops',
            name='t0',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Soldat', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='russian_troops',
            name='t1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Starshina', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='russian_troops',
            name='t10',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='T34', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='russian_troops',
            name='t11',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='KV2', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='russian_troops',
            name='t12',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Generalissmus', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='russian_troops',
            name='t13',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Political_commissar', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='russian_troops',
            name='t2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tupolev_ANT7', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='russian_troops',
            name='t3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MiG3', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='russian_troops',
            name='t4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sturmovik', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='russian_troops',
            name='t5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Submarine_russian', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='russian_troops',
            name='t6',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Glorious_battleship', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='russian_troops',
            name='t7',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Red_carrier', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='russian_troops',
            name='t8',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Katyusha', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='russian_troops',
            name='t9',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cannon_russian', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='report',
            name='attacker_village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.Village'),
        ),
        migrations.AddField(
            model_name='report',
            name='defenders',
            field=models.ManyToManyField(to='world.Defender'),
        ),
        migrations.AddField(
            model_name='queue',
            name='troop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.Troop'),
        ),
        migrations.AddField(
            model_name='port',
            name='queue',
            field=models.ManyToManyField(to='world.Queue'),
        ),
        migrations.AddField(
            model_name='player',
            name='last_village',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last', to='world.Village'),
        ),
        migrations.AddField(
            model_name='player',
            name='market_reports',
            field=models.ManyToManyField(null=True, to='world.Trading'),
        ),
        migrations.AddField(
            model_name='player',
            name='medals',
            field=models.ManyToManyField(null=True, to='world.Medals'),
        ),
        migrations.AddField(
            model_name='player',
            name='reports',
            field=models.ManyToManyField(null=True, to='world.Report'),
        ),
        migrations.AddField(
            model_name='player',
            name='scouting_reports',
            field=models.ManyToManyField(null=True, to='world.Scouting'),
        ),
        migrations.AddField(
            model_name='player',
            name='sitter_1',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_sitter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='player',
            name='sitter_2',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_sitter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='player',
            name='tribe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.Tribe'),
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='player',
            name='villages',
            field=models.ManyToManyField(null=True, to='world.Village'),
        ),
        migrations.AddField(
            model_name='partisan_troops',
            name='t0',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Volounteer', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='partisan_troops',
            name='t1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Senior_fighter', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='partisan_troops',
            name='t10',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tank_partisan', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='partisan_troops',
            name='t11',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Heavy_tank_partisan', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='partisan_troops',
            name='t12',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Marshall', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='partisan_troops',
            name='t13',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Colonel', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='partisan_troops',
            name='t2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Hot_air_baloon', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='partisan_troops',
            name='t3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Turbo_fan_fighter', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='partisan_troops',
            name='t4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bomber_partisan', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='partisan_troops',
            name='t5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Fishermen_boat', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='partisan_troops',
            name='t6',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Wooden_battleship', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='partisan_troops',
            name='t7',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Carrier_partisan', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='partisan_troops',
            name='t8',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Mortar_partisan', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='partisan_troops',
            name='t9',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cannon_partisan', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='oasis',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='world.Player'),
        ),
        migrations.AddField(
            model_name='message',
            name='recipent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Recipent', to='world.Player'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sender', to='world.Player'),
        ),
        migrations.AddField(
            model_name='market_offers',
            name='demanding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Want', to='world.Market_resources'),
        ),
        migrations.AddField(
            model_name='market_offers',
            name='offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Offer', to='world.Market_resources'),
        ),
        migrations.AddField(
            model_name='market_offers',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.Village'),
        ),
        migrations.AddField(
            model_name='market',
            name='quantity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.Market_resources'),
        ),
        migrations.AddField(
            model_name='market',
            name='recipent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Get', to='world.Village'),
        ),
        migrations.AddField(
            model_name='market',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Send', to='world.Village'),
        ),
        migrations.AddField(
            model_name='japanese_troops',
            name='t0',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Warrior', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='japanese_troops',
            name='t1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Samurai', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='japanese_troops',
            name='t10',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ha_Go', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='japanese_troops',
            name='t11',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='O_I', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='japanese_troops',
            name='t12',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Emperor', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='japanese_troops',
            name='t13',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Settler', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='japanese_troops',
            name='t2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Nakajima_C6N', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='japanese_troops',
            name='t3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Kamikaze', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='japanese_troops',
            name='t4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Kawasaki_Ki48', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='japanese_troops',
            name='t5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Submarine_japan', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='japanese_troops',
            name='t6',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Emperors_battleship', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='japanese_troops',
            name='t7',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Carrier_of_the_sun', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='japanese_troops',
            name='t8',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Mortar_japan', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='japanese_troops',
            name='t9',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cannon_japan', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='invited',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.Player'),
        ),
        migrations.AddField(
            model_name='hangar',
            name='queue',
            field=models.ManyToManyField(to='world.Queue'),
        ),
        migrations.AddField(
            model_name='german_troops',
            name='t0',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Wehrmacht_soldat', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='german_troops',
            name='t1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SS_soldat', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='german_troops',
            name='t10',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Panther', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='german_troops',
            name='t11',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tiger', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='german_troops',
            name='t12',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Fuhrer', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='german_troops',
            name='t13',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reich_Minister', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='german_troops',
            name='t2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Junkers_88D', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='german_troops',
            name='t3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Messerschmitt', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='german_troops',
            name='t4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Stuka', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='german_troops',
            name='t5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='U_boot', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='german_troops',
            name='t6',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Schiff', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='german_troops',
            name='t7',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='F_boot', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='german_troops',
            name='t8',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Mortar_german', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='german_troops',
            name='t9',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cannon_german', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='defender',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.Village'),
        ),
        migrations.AddField(
            model_name='brittish_troops',
            name='t0',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Soldier', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='brittish_troops',
            name='t1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Royal_marine', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='brittish_troops',
            name='t10',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MK6', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='brittish_troops',
            name='t11',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Medium_Mark_2', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='brittish_troops',
            name='t12',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Queen', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='brittish_troops',
            name='t13',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Prime_minister', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='brittish_troops',
            name='t2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Mosquito', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='brittish_troops',
            name='t3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Meteor', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='brittish_troops',
            name='t4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Avro_Lancaster', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='brittish_troops',
            name='t5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HM_Submarine', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='brittish_troops',
            name='t6',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HMSB_ship', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='brittish_troops',
            name='t7',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HMSC', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='brittish_troops',
            name='t8',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Mortar_brittish', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='brittish_troops',
            name='t9',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cannon_brittish', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='barracks',
            name='queue',
            field=models.ManyToManyField(to='world.Queue'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.Village'),
        ),
        migrations.AddField(
            model_name='army',
            name='t0',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Typeone', to='world.Troops'),
        ),
        migrations.AddField(
            model_name='army',
            name='t1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Typetwo', to='world.Troops'),
        ),
        migrations.AddField(
            model_name='army',
            name='t10',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Typeeleven', to='world.Troops'),
        ),
        migrations.AddField(
            model_name='army',
            name='t11',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Typetwelve', to='world.Troops'),
        ),
        migrations.AddField(
            model_name='army',
            name='t12',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Typethirteen', to='world.Troops'),
        ),
        migrations.AddField(
            model_name='army',
            name='t13',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Typefourteen', to='world.Troops'),
        ),
        migrations.AddField(
            model_name='army',
            name='t2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Typethree', to='world.Troops'),
        ),
        migrations.AddField(
            model_name='army',
            name='t3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Typefour', to='world.Troops'),
        ),
        migrations.AddField(
            model_name='army',
            name='t4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Typefive', to='world.Troops'),
        ),
        migrations.AddField(
            model_name='army',
            name='t5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Typesix', to='world.Troops'),
        ),
        migrations.AddField(
            model_name='army',
            name='t6',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Typeseven', to='world.Troops'),
        ),
        migrations.AddField(
            model_name='army',
            name='t7',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Typeeight', to='world.Troops'),
        ),
        migrations.AddField(
            model_name='army',
            name='t8',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Typenine', to='world.Troops'),
        ),
        migrations.AddField(
            model_name='army',
            name='t9',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Typeten', to='world.Troops'),
        ),
        migrations.AddField(
            model_name='american_troops',
            name='t0',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Private', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='american_troops',
            name='t1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Marine', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='american_troops',
            name='t10',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sherman', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='american_troops',
            name='t11',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Super_pershing', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='american_troops',
            name='t12',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='President', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='american_troops',
            name='t13',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Invader', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='american_troops',
            name='t2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DouglasO_31', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='american_troops',
            name='t3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Airacomet', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='american_troops',
            name='t4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='B_17', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='american_troops',
            name='t5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Submarine_american', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='american_troops',
            name='t6',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Great_battleship', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='american_troops',
            name='t7',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Carrier_american', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='american_troops',
            name='t8',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Mortar_american', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='american_troops',
            name='t9',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cannon_american', to='world.Troop'),
        ),
        migrations.AddField(
            model_name='ally_leadership',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.Player'),
        ),
        migrations.AddField(
            model_name='alliance',
            name='leadership',
            field=models.ManyToManyField(to='world.Ally_leadership'),
        ),
        migrations.AddField(
            model_name='alliance',
            name='medals',
            field=models.ManyToManyField(to='world.Medals'),
        ),
        migrations.AddField(
            model_name='alliance',
            name='member',
            field=models.ManyToManyField(to='world.Player'),
        ),
    ]
