# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 11:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_auto_20170528_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='coal_bonus_production',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 28, 11, 16, 57, 293364), verbose_name='Coal bonus production'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='food_bonus_production',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 28, 11, 16, 57, 293439), verbose_name='Food bonus production'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='iron_bonus_production',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 28, 11, 16, 57, 293284), verbose_name='Iron bonus production'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='oil_bonus_production',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 28, 11, 16, 57, 293201), verbose_name='Oil bonus production'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='plus_account',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 28, 11, 16, 57, 293091), verbose_name='Plus Account'),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 28, 11, 16, 57, 304362)),
        ),
        migrations.AlterField(
            model_name='village',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 28, 11, 16, 57, 288425), verbose_name='Last update time'),
        ),
    ]
