# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 16:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0003_auto_20170607_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='next_update',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='queue',
            name='next_update',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 7, 16, 19, 41, 838114)),
        ),
        migrations.AddField(
            model_name='village',
            name='next_update',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='coal_bonus_production',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 7, 16, 19, 41, 849953), verbose_name='Coal bonus production'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='food_bonus_production',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 7, 16, 19, 41, 849995), verbose_name='Food bonus production'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='iron_bonus_production',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 7, 16, 19, 41, 849908), verbose_name='Iron bonus production'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='oil_bonus_production',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 7, 16, 19, 41, 849860), verbose_name='Oil bonus production'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='plus_account',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 7, 16, 19, 41, 849799), verbose_name='Plus Account'),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 7, 16, 19, 41, 857681)),
        ),
        migrations.AlterField(
            model_name='village',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 7, 16, 19, 41, 844287), null=True, verbose_name='Last update time'),
        ),
    ]
